modules/account/controllers/AccountController.php
<?php

namespace app\modules\account\controllers;

use Yii;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
//use app\models\Newsletter;
//use app\models\Request;
use app\models\RequestType;
use yii\data\ArrayDataProvider;
use yii\web\Response;
use app\models\UserCustomer;
use app\models\Order;


class AccountController extends Controller {

    const PAGE_SIZE = 20;

    public function actionIndex() {
        return $this->render('index');
    }

    public function actionCustomers() {
        $customers = UserCustomer::findAllByPartner();
        
        $provider = new ArrayDataProvider([
            'allModels' => $customers,
            'sort' => [
//                'attributes' => ['id', 'email'],
            ],
            'pagination' => [
                'pageSize' => self::PAGE_SIZE,
            ],
        ]);

        return $this->render('customers', [
            'customers' => $provider
        ]);
    }
    
    public function actionOrders() {
        $orders = [];
        $customers = UserCustomer::findAllByPartner();
        if (!empty($customers)) {
            $orders = Order::findAllByUsers($customers);
        }
        
        $sum = 0;
        if (!empty($orders)) {
            foreach ($orders as $order) {
                $sum += $order->ticket->type->price;
            }
            $sum = number_format($sum / 100 * 10, 2, '.', '');
        }

        $provider = new ArrayDataProvider([
            'allModels' => $orders,
            'sort' => [
//                'attributes' => ['id', 'email'],
            ],
            'pagination' => [
                'pageSize' => self::PAGE_SIZE,
            ],
        ]);

        return $this->render('orders', [
            'orders' => $provider,
            'sum' => $sum
        ]);
    }

//    public function actionRequestStatus() {
//        if (Yii::$app->request->isAjax) {
//            $response = false;
//
//            $id = (int)Yii::$app->request->getQueryParams()['id'];
//            $value = (int)Yii::$app->request->getQueryParams()['value'];
//
//            $requests = Request::findOne($id);
//            $requests->status = $value;
//            if ($requests->update() !== false) {
//                $response = true;
//            }
//
//            Yii::$app->response->format = Response::FORMAT_JSON;
//            return [
//                'status' => $response,
//            ];
//        }
//        Yii::$app->end();
//    }

//    public function actionDelete() {
//        if (Yii::$app->request->isAjax) {
//            $response = false;
//
//            $model = Yii::$app->request->getQueryParams()['model'];
//            $id = (int)Yii::$app->request->getQueryParams()['id'];
//
//            switch ($model) {
//                case 'request':
//                    $delete = new Request();
//                    break;
//                default:
//                    return false;
//            }
//
//            $delete = $delete->findOne($id);
//            if ($delete) {
//                if ($delete->delete() !== false) {
//                    $response = true;
//                }
//            }
//
//            Yii::$app->response->format = Response::FORMAT_JSON;
//            return [
//                'status' => $response,
//            ];
//        }
//        Yii::$app->end();
//    }


}

modules/account/views/layouts/main.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\modules\account\assets\AccountAsset;

AccountAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html class="fuelux">
<head>
    <meta charset="UTF-8">
    <?php echo Html::csrfMetaTags() ?>
    <title><?php echo $this->title; ?></title>
    <?php $this->head() ?>
    <link rel="icon" type="image/png" href="/images/16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="/images/24.png" sizes="24x24">
    <link rel="icon" type="image/png" href="/images/32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/images/48.png" sizes="48x48">
    <link rel="icon" type="image/png" href="/images/64.png" sizes="64x64">
    <link rel="icon" href="/images/favicon.ico">
</head>
<body>
<?php $this->beginBody() ?>
<?php
NavBar::begin([
    'brandLabel' => Yii::$app->name,
    'brandUrl' => Yii::$app->homeUrl,
    'options' => [
        'class' => 'navbar-inverse navbar-fixed-top',
    ],
]);
if (Yii::$app->user->can('accountPermission')) {
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'encodeLabels' => false,
        'items' => [
            ['label' => 'Заказы', 'url' => ['/account/orders']],
            ['label' => 'Покупатели', 'url' => ['/account/customers']],
            ['label' => Yii::$app->user->identity->login,
                'url' => ['#'],
                'items' => [
                    ['label' => 'Профиль', 'url' => ['/account']],
                    '<li class="divider"></li><li>'
                    . Html::beginForm(['/logout'], 'post')
                    . Html::submitButton(
                        'Выйти',
                        ['class' => 'btn btn-secondary col-lg-12']
                    )
                    . Html::endForm()
                    . '</li>'
                ]
            ]
        ],
    ]);
}
NavBar::end();
?>
<div class="container content">
    <div class="row-fluid">
        <div>
            <?php echo $content ?>
        </div>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>