modules/admin/controllers/AdminController.php
<?php

namespace app\modules\admin\controllers;

use app\models\Ticket;
use app\models\UserCustomer;
use Yii;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use app\models\Newsletter;
use app\models\Request;
use app\models\RequestType;
use yii\data\ArrayDataProvider;
use yii\web\Response;
use app\models\User;
use app\models\Order;
//use yii\db\Query;


class AdminController extends Controller {

    const PAGE_SIZE = 20;

    public function actionIndex() {
        return $this->render('index');
    }

    public function actionNewsletter() {
        $newsletter = Newsletter::getAll();

        $provider = new ArrayDataProvider([
            'allModels' => $newsletter,
            'sort' => [
                'attributes' => ['id', 'email'],
            ],
            'pagination' => [
                'pageSize' => self::PAGE_SIZE,
            ],
        ]);

        return $this->render('newsletter', [
            'emails' => $provider
        ]);
    }

    public function actionWriteUs() {
        $searchModel = new Request();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
//
        return $this->render('write_us', [
            'requests' => $dataProvider,
            'searchModel' => $searchModel
        ]);
    }

    public function actionRequestStatus() {
        if (Yii::$app->request->isAjax) {
            $response = false;

            $id = (int)Yii::$app->request->getQueryParams()['id'];
            $value = (int)Yii::$app->request->getQueryParams()['value'];

            $requests = Request::findOne($id);
            $requests->status = $value;
            if ($requests->update() !== false) {
                $response = true;
            }

            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'status' => $response,
            ];
        }
        Yii::$app->end();
    }

    public function actionDelete() {
        if (Yii::$app->request->isAjax) {
            $response = false;

            $model = Yii::$app->request->getQueryParams()['model'];
            $id = (int)Yii::$app->request->getQueryParams()['id'];

            switch ($model) {
                case 'request':
                    $delete = new Request();
                    break;
                default:
                    return false;
            }

            $delete = $delete->findOne($id);
            if ($delete) {
                if ($delete->delete() !== false) {
                    $response = true;
                }
            }

            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'status' => $response,
            ];
        }
        Yii::$app->end();
    }

    public function actionPartners() {
        $partners = User::getUsersWithAccountRole();

        $provider = new ArrayDataProvider([
            'allModels' => $partners,
            'sort' => [
                'attributes' => ['id', 'login'],
            ],
            'pagination' => [
                'pageSize' => self::PAGE_SIZE,
            ],
        ]);
        return $this->render('partners', [
            'partners' => $provider
        ]);
    }
    
    public function actionOrders() {
        $partners = User::getUsersWithAccountRole();

        $provider = new ArrayDataProvider([
            'allModels' => $partners,
            'pagination' => [
                'pageSize' => self::PAGE_SIZE,
            ],
        ]);

        return $this->render('orders', [
            'partners' => $provider
        ]);
    }

    public function actionCame() {
        if (Yii::$app->request->isAjax && Yii::$app->request->post()) {
            $res = false;

            $id = Yii::$app->request->post('id');
            $came = Yii::$app->request->post('value');

            if (!empty($id)) {
                $ticket = Ticket::findOne($id);
                $ticket->came = $came;
                if ($ticket->save() !== false) {
                    $res = true;
                }
            }

            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'status' => $res,
            ];
        }
    }

    public function actionTickets() {
        $sum = 0;
        $tickets = Ticket::getBought();

        if (!empty($tickets)) {
            foreach ($tickets as $ticket) {
                $sum += $ticket->type->price;
            }
        }

        $searchModel = new Ticket();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('tickets', [
            'tickets' => $dataProvider,
            'searchModel' => $searchModel,
            'sum' => $sum
        ]);
    }
    
}

modules/admin/views/admin/index.php
Добро пожаловать в админку!

modules/admin/views/admin/newsletter.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\ActiveForm;
//use app\components\StatisticsMenu;

/* @var $this yii\web\View */
/* @var $tmClasses yii\data\ActiveDataProvider */
/* @var $rClasses yii\data\ActiveDataProvider */

$this->title = 'Список email-адресов';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="stat row">
    <div class="stat-content">
        <h1><?php echo Html::encode($this->title); ?></h1>
        
        <?= GridView::widget([
            'dataProvider' => $emails,
            'summary' => '',
            'formatter' => ['class' => 'yii\i18n\Formatter', 'nullDisplay' => ''],
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'id:text:ID',
                'email:text:Email',
            ],
        ]) ?>
    </div>
</div>

modules/admin/views/admin/orders.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\ActiveForm;
//use app\components\StatisticsMenu;

/* @var $this yii\web\View */
/* @var $tmClasses yii\data\ActiveDataProvider */
/* @var $rClasses yii\data\ActiveDataProvider */

$this->title = 'Партнёры > Заказы';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="stat row">
    <div class="stat-content">
        <h1><?php echo Html::encode($this->title); ?></h1>

        <?= GridView::widget([
            'dataProvider' => $partners,
            'summary' => '',
            'formatter' => ['class' => 'yii\i18n\Formatter', 'nullDisplay' => ''],
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'id:text:ID',
                [
                    'label' => 'Партнёр',
                    'value' => function($model) {
                        return $model->login;
                    }
                ],
                [
                    'label' => 'Клиенты',
                    'value' => function($model) {
                        if (isset($model->orders)) {
                            $users = [];
                            foreach ($model->orders as $order) {
                                $users[] = $order->customer->email;
                            }
                            return implode('<br>', $users);
                        }
                    },
                    'format' => 'raw',
                ],
                [
                    'label' => 'Выплатить',
                    'value' => function($model) {
                        $sum = 0;

                        if (isset($model->orders)) {
                            foreach ($model->orders as $order) {
                                if (isset($order->customer->orders)) {
                                    foreach ($order->customer->orders as $ticket) {
                                        $price = $ticket->ticket->type->price;
                                        $sum += $price;
                                    }
                                }
                            }
                            if ($sum > 0) {
                                return $sum / 100 * 10;
                            }
                        }
                        return 0;
                    },
                ]
            ],
        ]) ?>
    </div>
</div>

modules/admin/views/admin/partners.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
//use app\components\StatisticsMenu;

/* @var $this yii\web\View */
/* @var $tmClasses yii\data\ActiveDataProvider */
/* @var $rClasses yii\data\ActiveDataProvider */

$this->title = 'Партнёры > Список';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="stat row">
    <div class="stat-content">
        <h1><?php echo Html::encode($this->title); ?></h1>

        <?= GridView::widget([
            'dataProvider' => $partners,
            'summary' => '',
            'formatter' => ['class' => 'yii\i18n\Formatter', 'nullDisplay' => ''],
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'id:text:ID',
                'login:text:Email',
                [
                    'label' => 'Ссылка',
                    'value' => function($model) {
                        return '<code>' . Yii::$app->urlManager->hostInfo . Url::to(['/', 'link' => $model->link]) . '</code>';
                    },
                    'format' => 'raw',
                ]
            ],
        ]) ?>
    </div>
</div>

modules/admin/views/admin/tickets.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
//use app\components\StatisticsMenu;

/* @var $this yii\web\View */
/* @var $tmClasses yii\data\ActiveDataProvider */
/* @var $rClasses yii\data\ActiveDataProvider */

$this->title = 'Заказы';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="stat row">
    <div class="stat-content">
        <h1><?php echo Html::encode($this->title); ?></h1>

        <?= GridView::widget([
            'dataProvider' => $tickets,
            'filterModel' => $searchModel,
            'summary' => '',
            'formatter' => ['class' => 'yii\i18n\Formatter', 'nullDisplay' => ''],
            'showFooter' => true,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'id:text:ID билета',
                [
                    'attribute' => 'ticketOrder',
                    'label' => '№ Заказа',
                    'value' => function ($model, $key, $index, $column) {
                        return $model->order->id;
                    },
                ],
                [
                    'attribute' => 'ticketNumber',
                    'label' => '№ билета',
                    'value' => function ($model, $key, $index, $column) {
                        return $model->number;
                    },
                    'format' => 'html',
                ],
                [
                    'attribute' => 'ticketName',
                    'label' => 'Покупатель',
                    'value' => function ($model, $key, $index, $column) {
                        return $model->order->client->name;
                    },
                ],
                [
                    'attribute' => 'ticketEmail',
                    'label' => 'Email',
                    'value' => function ($model, $key, $index, $column) {
                        return $model->order->client->email;
                    },
                ],
                [
                    'label' => 'Тип билета',
                    'value' => function ($model, $key, $index, $column) {
                        return $model->type->name;
                    },
                    'format' => 'html',
                ],
                [
                    'label' => 'Цена билета',
                    'value' => function ($model, $key, $index, $column) {
                        return $model->type->price;
                    },
                    'footer' => $sum
                ],
                [
                    'label' => 'Пришёл',
                    'value' => function ($model, $key, $index, $column) {
                        return Html::checkbox('came', $model->came, ['value' => $model->came, 'class' => 'came', 'data-id' => $model['id']]);
                    },
                    'format' => 'raw',
                ],
            ],
        ]) ?>
    </div>
</div>

modules/admin/views/admin/write_us.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\ActiveForm;
use yii\jui\DatePicker;
use yii\helpers\Url;
//use app\components\StatisticsMenu;

/* @var $this yii\web\View */
/* @var $tmClasses yii\data\ActiveDataProvider */
/* @var $rClasses yii\data\ActiveDataProvider */

$this->title = 'Связаться с нами';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="stat row">
    <div class="stat-content">
        <h1><?php echo Html::encode($this->title); ?></h1>

        <?= GridView::widget([
            'dataProvider' => $requests,
            'summary' => '',
            'filterModel' => $searchModel,
            'formatter' => ['class' => 'yii\i18n\Formatter', 'nullDisplay' => ''],
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'id:text:ID',
                'email:text:Email',
                'text:text:Сообщение',
                [
                    'label' => 'Дата',
                    'attribute' => 'created_at',
                    'filter' => '<div class="form-group">' . DatePicker::widget([
                            'language' => 'ru',
                            'model' => $searchModel,
                            'attribute' => 'created_at',
                            'dateFormat' => 'dd-MM-yyyy',
                            'options' => [
                                'class' => 'form-control'
                            ]
                        ]). '</div>',
                    'format' =>  ['date', 'dd-MM-Y HH:mm:ss']
                ],
                [
                    'label' => 'Статус',
                    'attribute' => 'status',
                    'value' => function ($model, $key, $index, $column) {
//                        return $model->status ? 'Обработано' : 'Не обработано';
                        return '<div class="btn-group-vertical">
                            <a class="btn btn-primary btn-xs btn-activate" data-value="' . ($model->status ? 0 : 1) . '" data-id="' . $model->id . '">
                                <span>' . ($model->status ? 'Обработано' : 'Не обработано') . '</span>
                                <div class="progress progress-striped active" style="border-radius: 0;margin: 0;height: 3px; display: none">
                                    <div class="progress-bar" style="width: 100%"></div>
                                </div>
                            </a>
                            <a class="btn btn-danger btn-xs btn-delete" data-id="' . $model->id . '">
                                Удалить
                                <div class="progress progress-striped active" style="border-radius: 0;margin: 0;height: 3px; display: none">
                                    <div class="progress-bar progress-bar-danger" style="width: 100%"></div>
                                </div>
                            </a>
                        </div>';
                    },
                    'format' => 'raw',
                ]
            ],
        ]) ?>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('.btn-activate').click(function () {
            var $this = $(this);
            var value = $this.attr('data-value');
            var id = $this.data().id;
            $this.find('.progress').show();
            $.ajax({
                url: '<?php echo Url::to('request-status'); ?>',
                type: 'get',
                dataType: 'json',
                data: {id: id, value: value},
                success: function (response) {
                    if (response.status == true) {
                        if (value == 1) {
                            $this.find('span').text('Обработана');
                            $this.attr('data-value', 0);
                        } else {
                            $this.find('span').text('Не обработана');
                            $this.attr('data-value', 1);
                        }
                    }
                    $this.find('.progress').hide();
                },
                error: function () {
                    $this.find('.progress').hide();
                }
            });
        });

        $('.btn-delete').click(function () {
            var agree = confirm('Вы действительно хотите удалить этот пункт?');
            if (agree) {
                var $this = $(this);
                deleteAjax($this, '<?php echo Url::to('delete'); ?>', 'request');
            }
        });
    });
</script>

modules/admin/views/layouts/main.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\modules\admin\assets\AdminAsset;

AdminAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html class="fuelux">
<head>
    <meta charset="UTF-8">
    <?php echo Html::csrfMetaTags() ?>
    <title><?php echo $this->title; ?></title>
    <?php $this->head() ?>
    <link rel="icon" type="image/png" href="/images/16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="/images/24.png" sizes="24x24">
    <link rel="icon" type="image/png" href="/images/32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/images/48.png" sizes="48x48">
    <link rel="icon" type="image/png" href="/images/64.png" sizes="64x64">
    <link rel="icon" href="/images/favicon.ico">
</head>
<body>
<?php $this->beginBody() ?>
<?php
NavBar::begin([
    'brandLabel' => Yii::$app->name,
    'brandUrl' => Yii::$app->homeUrl,
    'options' => [
        'class' => 'navbar-inverse navbar-fixed-top',
    ],
]);
if (Yii::$app->user->can('adminPermission')) {
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'encodeLabels' => false,
        'items' => [
            ['label' => 'Заказы',
                'url' => ['/admin/tickets'],
            ],
            ['label' => 'Партнёры',
                'url' => ['#'],
                'items' => [
                    ['label' => 'Список', 'url' => ['/admin/partners']],
                    ['label' => 'Заказы', 'url' => ['/admin/orders']],
                ],
            ],
            ['label' => 'Заявки',
                'url' => ['#'],
                'items' => [
                    ['label' => 'Связаться с нами', 'url' => ['/admin/write-us']],
                ],
            ],
            ['label' => 'Рассылка',
                'url' => ['#'],
                'items' => [
                    ['label' => 'Список email-адресов', 'url' => ['/admin/newsletter']],
                ],
            ],
            '<li id="exit">'
            . Html::beginForm(['/logout'], 'post')
            . Html::submitButton(
                'Выйти',
                ['class' => 'btn btn-secondary col-lg-12']
            )
            . Html::endForm()
            . '</li>'
        ],
    ]);
} 
NavBar::end();
?>
<div class="container content">
    <div class="row-fluid">
        <div>
            <?php echo $content ?>
        </div>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>